apiVersion: batch/v1
kind: Job
metadata:
  name: todoapi-functional-tests
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
        - name: functionaltests-storage
          persistentVolumeClaim:
            claimName: test-results-storage-claim
      containers:
        - name: todoapi-functionaltests
          image: ghcr.io/ramanathan23/todolistapi-functionaltests:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/testresults/"
              name: functionaltests-storage
      restartPolicy: Never
  backoffLimit: 1
