apiVersion: batch/v1
kind: Job
metadata:
  name: todoapi-functional-tests
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: todoapi-functionaltests
          image: ghcr.io/ramanathan23/todolistapi-functionaltests:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 1
