apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-test-app
  annotations:
    argocd.argoproj.io/hook: PostSync 
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: httpie
          image: alpine/httpie:2.4.0
          imagePullPolicy: Always
          command: ["http"]
          args:
            [
              "GET",
              "google.com"
            ]
      restartPolicy: Never
  backoffLimit: 1

