apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-results-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/test/results"
